tempMVC/Models/ErrorViewModel.cs
using System;

namespace tempMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
    

tempMVC/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace tempMVC.Models{
public class Student
{
    [Key]
    public Int16 StudentId { get; set;}

    [Required]
    public string Name { get; set;}

    [Required]
    public string Class { get; set;}

    [ForeignKey("Subject")]
    [Display(Name ="Subject")]
    
    public int SubjectId { get; set;}
    
    public virtual Subject Subject { get; set;}

}
}

tempMVC/Models/Subject.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
public class Subject
{
    [Key]

    public int ID { get;  set;}

    public string Subject_Name { get; set;}

    public string Syllabus { get; set;}

    [Range(1,5)]

    public int credits {get; set;}

}

tempMVC/Models/Teacher.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tempMVC.Models{
public class Teacher
{
     [Key]
    public int ID { get; set;}

    public string name { get; set;}

    public DateTime joindate { get; set;}

    public DateTime birthdate { get; set;}
}
}

tempMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tempMVC.Models;

namespace tempMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tempMVC/Controllers/StudentController.cs
using tempMVC;
using tempMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using tempMVC.data;

namespace tempMVC.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDBContext _db;

        public StudentController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Student> listofsubjects = _db.Student;
            return View(listofsubjects);
        }

        [HttpGet]
        public IActionResult Edit(int Studentid)
        {
            var subobj = _db.Student.Find(Studentid);
            return View(subobj);

        }

        [HttpPost]
        public IActionResult Edit(Student updatedvaluesobj)
        {
            _db.Student.Update(updatedvaluesobj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }


               //Get Delete
        public IActionResult Delete(int Studentid)
        {

            var studobj = _db.Student.Find(Studentid);
            return View(studobj);
        }


        [HttpPost]
        public IActionResult DeletePost(int ID)
        {
            var studobj = _db.Student.Find(ID);

            if (ModelState.IsValid)
            {

                _db.Student.Remove(studobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studobj);
        }





       
    }
}

tempMVC/Controllers/TeacherController.cs
using tempMVC;
using tempMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using tempMVC.data;
using Microsoft.EntityFrameworkCore;

namespace tempMVC.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ApplicationDBContext _db;

        public TeacherController(ApplicationDBContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(string searchString) {
            var teachers = from t in _db.Teacher
            select t;
            if (!String.IsNullOrEmpty(searchString)) {
                teachers = teachers.Where(s => s.name.Contains(searchString));
            }
            return View(await teachers.ToListAsync());
        }

         [HttpGet]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public IActionResult New(Teacher newTeacher)
        {
            _db.Teacher.Add(newTeacher);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
        
        [HttpGet]
        public IActionResult Edit(int teacherid)
        {
            var subobj = _db.Teacher.Find(teacherid);
            return View(subobj);

        }

        [HttpPost]
        public IActionResult Edit(Teacher updatedvaluesobj)
        {
            _db.Teacher.Update(updatedvaluesobj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }


               //Get Delete
        public IActionResult Delete(int Teacherid)
        {

            var studobj = _db.Teacher.Find(Teacherid);
            return View(studobj);
        }


        [HttpPost]
        public IActionResult DeletePost(int ID)
        {
            var studobj = _db.Teacher.Find(ID);

            if (ModelState.IsValid)
            {

                _db.Teacher.Remove(studobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studobj);
        }





       
    }
}

tempMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
   <b> <h1 class="display-4">Student Managment System</h1></b>
   <button type="button" class="btn btn-primary">Student</button>
   <button type="button" class="btn btn-primary">Teacher</button>
   <button type="button" class="btn btn-primary">Subject</button>
   <button type="button" class="btn btn-primary">Lab</button>
   
   
   
</div>


tempMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcPrac</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcPrac.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>Student Managment System</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Student Managment System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

tempMVC/Views/Student/Create.cshtml
@model tempMVC.Models.Student

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Student</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Class"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Class" class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>
-
                </div>
                  <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Subject" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId">
                            <option value="">--Select Subject--</option>
                        </select>
                        
                        <span asp-validation-for="SubjectId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

tempMVC/Views/Student/Delete.cshtml
@model tempMVC.Models.Student

<form method="post" asp-action="DeletePost">
    <input asp-for="StudentId" hidden />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Student Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Class"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Class" disabled class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}


tempMVC/Views/Student/Edit.cshtml
@model tempMVC.Models.Student

<form method="post" asp-action="Edit">
    <input asp-for="StudentId" hidden />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Student Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Class"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Class" class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}


tempMVC/Views/Student/Index.cshtml
@model IEnumerable<tempMVC.Models.Student>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary">Student List</h2>
        </div>
        <a asp-controller="Student" asp-action="Create" class="btn btn-primary">
            Create New Student
        </a>
    </div>
    <br/>
    @if(Model.Count() > 0)
            {
                <table class="table table-bordered table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>Student Name</th><th>Class</th><th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var obj1 in Model)
                {
                    <tr><td width="50%">@obj1.Name</td>
                    <td>@obj1.Class</td><td>
    <a class="btn btn-primary" asp-route-id="@obj1.StudentId" asp-controller="Student" asp-action="Edit">Edit</a>
    <a class="btn btn-primary" asp-route-id="@obj1.StudentId" asp-controller="Student" asp-action="Delete">Delete</a>
</td></tr>
                }
                    </tbody>
                </table>
            }
    else
    {
    <p> No student details.</p>
    }
    </div>

tempMVC/Views/Teacher/Delete.cshtml
@model tempMVC.Models.Teacher

<form method="post" asp-action="DeletePost">
      <input asp-for="ID" hidden />
    <input hidden asp-for="ID" />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Teacher </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="ID"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ID" class="form-control" />
                        <span asp-validation-for="ID" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="name">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="name" class="form-control" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="joindate">Joining Date</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="joindate" class="form-control" />
                        <span asp-validation-for="joindate" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="birthdate">Birth Date</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="birthdate" class="form-control" />
                        <span asp-validation-for="birthdate" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Delete Details" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

@{
    <partial name="_ValidationScriptsPartial" />
}

}

tempMVC/Views/Teacher/Edit.cshtml
@model tempMVC.Models.Teacher

<form method="post" asp-action="Edit">
    <input hidden asp-for="ID" />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Teacher </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="ID"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ID" class="form-control" />
                        <span asp-validation-for="ID" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="name">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="name" class="form-control" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="joindate">Joining Date</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="joindate" class="form-control" />
                        <span asp-validation-for="joindate" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="birthdate">Birth Date</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="birthdate" class="form-control" />
                        <span asp-validation-for="birthdate" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update subject Details" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

@{
    <partial name="_ValidationScriptsPartial" />
}

}

tempMVC/Views/Teacher/Index.cshtml
@model IEnumerable<tempMVC.Models.Teacher>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary">Teacher List</h2>
        </div>
        <a asp-controller="Teacher" asp-action="New" class="btn btn-primary">Add New Teacher</a>
    </div>
    <form asp-controller="Teacher" asp-action="Index">
        <p>
            Name: <input type="text" name="searchString"/>
            <input type="submit" value="Filter">
        </p>
    </form>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Teacher Id</th>
                    <th>Teacher Name</th>
                    <th>Teacher join date</th>
                    <th>Teacher birth date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj1 in Model)
                {
                    <tr>
                        <td width="50%">@obj1.ID</td>
                        <td>@obj1.name</td>
                        <td>@obj1.joindate</td>
                        <td>@obj1.birthdate</td>
                        <td>
                           <a asp-controller="Teacher" asp-action="Edit" asp-route-Teacherid="@obj1.ID" class="btn btn-primary">Edit</a>
                            <a asp-controller="Teacher" asp-action="Delete" asp-route-Teacherid="@obj1.ID" class="btn btn-primary">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No subject details.</p>
    }
</div>


tempMVC/Views/Teacher/New.cshtml
@model tempMVC.Models.Teacher

<form method="post" asp-action="New">
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add New Teacher </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="ID"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ID" class="form-control" />
                        <span asp-validation-for="ID" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="name">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="name" class="form-control" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="joindate">Joining Date</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="joindate" class="form-control" />
                        <span asp-validation-for="joindate" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="birthdate">Birth Date</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="birthdate" class="form-control" />
                        <span asp-validation-for="birthdate" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Add New Teacher" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

@{
    <partial name="_ValidationScriptsPartial" />
}

}